import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@ejpb/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Book Finder App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="bg-gray-500 font-thin">Hello World!</h1>
      </main>
    </>
  );
}
